# This is a basic workflow to help you get started with Actions

name: Build docker image

# Controls when the workflow will run
on:
  # Triggers the workflow.
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Stracts the name of the branch
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Echo the branch name (debug)
        run: echo product-innovation-radar:${{ steps.extract_branch.outputs.branch }}

      # Runs a single command using the runners shell
      - name: Docker build
        run: docker build -t product-innovation-radar:${{ steps.extract_branch.outputs.branch }}

